### ISSUE TITLE
Replace Products default layouts in SQL import with `juicy-style` layout hints

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Products#10]
Replace default layouts from SQL import ([default-layout.sql](https://github.com/StarcounterSamples/Products/blob/master/src/Products/Content/default-layout.sql)) to inline styles (https://starcounter.gitbooks.io/rebelslounge/content/layout_hinting.html).

This is a reference job that will be repeated in other apps by someone else.

**Comment by tomalec** [comment]
I have change provided the layout hints all pages except `EditProductPage.html` looks exactly the same. 
For `EditProductPage.html` my results looks as follows:

**reference**, default layout provided via SQL: ![default layout sql](https://cloud.githubusercontent.com/assets/17435/14251478/89d9a7bc-fa83-11e5-8601-04f995d8fc56.png)
**clean layouts** (just after `delete from Starcounter.Layout`):
![layout hints](https://cloud.githubusercontent.com/assets/17435/14251477/89d71092-fa83-11e5-9f6c-24f4a92af386.png)
**after applying gutter** = 15, manually: 
![layout hints with gutter](https://cloud.githubusercontent.com/assets/17435/14251476/89acb11c-fa83-11e5-84b5-fc8acc796388.png)

- I have moved next, prev buttons to separate row, as we do not have cell alignment yet (3x3 control), so it will not look ugly for very long and very short names of next item.
- There is no way to set gutter for entire partial from single app response, so we need to set it manually.
- There is no way to specify groups with layout hints, but those were not needed here.


@warpech Does it look good? Can I remove entire SQL-related code, or do we want it to provide gutter?

**Comment by tomalec** [comment]
BTW, I would say that it did uglified code a little bit https://github.com/StarcounterSamples/Products/blob/238ed8db2e91435d71cfd5261f5592493a404fbc/src/Products/wwwroot/Products/viewmodels/EditProductPage.html

**Comment by warpech** [comment]
@tomalec can this be closed?

**Comment by tomalec** [comment]
@warpech are you okay, with the result I presented above, or should we try to somehow achieve exact same layout as with SQL (gutters, groups)?

**Comment by warpech** [comment]
I am fine with what is there right now. The remainings need separate issues:

> I have moved next, prev buttons to separate row, as we do not have cell alignment yet (3x3 control), so it will not look ugly for very long and very short names of next item.

Issues already exist: https://github.com/Juicy/juicy-tile-editor/issues/121, https://github.com/Juicy/juicy-tile-grid/issues/20

>There is no way to set gutter for entire partial from single app response, so we need to set it manually.

Is there an issue for that? If I understand correctly, think there should be some hinting on the level of `starcounter-include`.

**Comment by tomalec** [comment]
> Is there an issue for that? If I understand correctly, think there should be some hinting on the level of starcounter-include.

There is no issue for that, I just want to make sure that you are aware of such result, and that is what we desire.

And I don't think it could be on `sc-include` level, as app developer of a partial, is not aware of any insertion point of his content.

**Comment by warpech** [comment]
> And I don't think it could be on sc-include level, as app developer of a partial, is not aware of any insertion point of his content.

Maybe this is right. Let's skip it for now then

**Comment by warpech** [comment]
@tomalec I think you forgot to remove the code that imports SQL layouts. It is redundant now:

- https://github.com/StarcounterSamples/Products/blob/master/src/Products/Helpers/DefaultStyles.cs
- https://github.com/StarcounterSamples/Products/blob/master/src/Products/Content/default-layout.sql
