### ISSUE TITLE
Apply BEM to Products's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Products#11]
Continuing our effort to implement https://github.com/Starcounter/Starcounter/issues/3450 in our sample apps, we should make changes to the Products app to follow the BEM CSS pattern.

I have yet not written the blog post about it (it is on me - https://github.com/Starcounter/starcounter.io/issues/143), but here are some principles to follow:

1. Only apply BEM to CSS styles defined in private CSS of the app. So apply it here: `wwwroot/Products`, but not here: `wwwroot/sys`
2. The only valid BEM selectors are class selectors. Get rid of all the id and element selectors.
3. It is ok for apps to be using Bootstrap selectors (which are found here: https://github.com/Starcounter/Starcounter/blob/develop/src/BuildSystem/ClientFiles/StaticFiles/sys/bootswatch/paper/bootstrap.css). It is not OK for an app (such as Products) to modify these classes. If you want to modify an element that uses a Bootstrap class, add another BEM-style class to it and modify that one.

Some practical information might also be found in the review of applying BEM to KitchenSink, which I did here: https://github.com/StarcounterSamples/KitchenSink/issues/19

**Comment by warpech** [comment]
@ubbeK I am not sure which of these might be unclear to you, so just please ask ask ask if you need me to clarify anything.

**Comment by ubbeK** [comment]
Currently working on the fix on branch: https://github.com/StarcounterSamples/Products/tree/feature_product_BEM_issue_11

**Comment by ubbeK** [comment]
Fix is ready for review @ https://github.com/StarcounterSamples/Products/tree/feature_product_BEM_issue_11

I noticed that EditProductPage.html is not compatible with the Launcher:
![editproductpage](https://cloud.githubusercontent.com/assets/8124023/14321300/f3122132-fc18-11e5-91aa-e4dba2f80e02.PNG)

**Comment by warpech** [comment]
Thanks for reporting! This time it is actually not a bug, just probably you have some custom styles that were applied from Products `3.0.4` (installed from App Warehouse). 
> I noticed that EditProductPage.html is not compatible with the Launcher:

Due to recent commits in Products `master` by @tomalec (https://github.com/StarcounterSamples/Products/issues/10), these styles need to be reset manually. To fix this, click the "Paintbrush" icon in the top right corner of Launcher and press "Reset" button, then "Save". You should see something like this afterwards:

<img width="1434" alt="screen shot 2016-04-07 at 00 29 31" src="https://cloud.githubusercontent.com/assets/566463/14334970/2a0a37c6-fc58-11e5-9d01-8542948902eb.png">

**Comment by warpech** [comment]
Regarding your changes, just two comments:

1. class `.products-form__heading-label` is incorrect, because there is no BEM Block called "products-form". I think this needs to be propagated to a BEM Block of its own. Maybe  `.products-box-heading-label`, to make it appear related to other "boxes".
2. let's try to find more meaningful name for `.products-div`. Wouldn't `.products-current-page` be better?

Good job!

**Comment by ubbeK** [comment]
Will fix it after the meeting @ 10:00.

@warpech: I got another question. I have seen that the supplier, which is connected to the product, is shown twice when the application is running in standalone mode. Do I have to make a new issue to solve these kind of bugs or is it OK to fix it within this issue?
![editproductpage_standalone_suppliernameshowntwice](https://cloud.githubusercontent.com/assets/8124023/14344233/a95339b2-fca6-11e5-98e5-fb89007a49c3.PNG)

**Comment by warpech** [comment]
> @warpech: I got another question. I have seen that the supplier, which is connected to the product, is shown twice when the application is running in standalone mode. Do I have to make a new issue to solve these kind of bugs or is it OK to fix it within this issue?

Interesting finding. Please find always report a new issue in such cases.

**Comment by tomalec** [comment]
I think the reason is that the first "organization" comes from `ProductSupplierPage.html` that attaches the supplier (one of existing) to a product, and loads another partial for this supplier details; the second one comes from `SupplierPage.html` which is the partial for supplier. I wonder whether it's a leftover from the times when Suppliers where managed by Products app, or do we still want to expose supplier partial by Product?

**Comment by warpech** [comment]
Ah right, so that element is also present when Launcher is running, but is hidden because of "duck shooting". I added a not to explain "duck shooting" in: https://github.com/Starcounter/starcounter.io/issues/149

**Comment by ubbeK** [comment]
Fixes 

> class .products-form__heading-label is incorrect, because there is no BEM Block called "products-form". I think this needs to be propagated to a BEM Block of its own. Maybe .products-box-heading-label, to make it appear related to other "boxes".
let's try to find more meaningful name for .products-div. Wouldn't .products-current-page be better?

ready for review @ https://github.com/StarcounterSamples/Products/tree/feature_product_BEM_issue_11

**Comment by tomalec** [comment]
> Ah right, so that element is also present when Launcher is running,

it is

> but is hidden because of "duck shooting". I added a not to explain "duck shooting"

Entire partial is hidden in layout hint, as it was hidden with default layout given in SQL
https://github.com/StarcounterSamples/Products/blob/feature_product_BEM_issue_11/src/Products/wwwroot/Products/viewmodels/ProductSupplierPage.html#L21

My question is whether we need this partial here or not? I think that providing a (visual) widget that is  hidden by default, only increases confusion.

So I would either:
1. Make `<starcounter-include>` visible bu default (via layout hint), but remove `SupplierPage.html` - other apps would be able to put smth there, but Products won't duplicate itself.
2. Remove both `<starcounter-include>` for supplier partial, and `SupplierPage.html`

I do not find a reason to keep `SupplierPage.html` in this app.

**Comment by warpech** [comment]
@tomalec I have moved the discussion about this partial to #12.

@ubbeK You changed not the class that I requested. I proposed to change `.products-form__heading-label` to `.products-box-heading-label`. You changed `.products-top-menu__list-item` to `products-box-heading-label`.

**Comment by ubbeK** [comment]
@warpech Change is now committed @ https://github.com/StarcounterSamples/Products/commit/47e1ddc8a5d854f2b34d69454b6de6cf5ad6e416

**Comment by warpech** [comment]
Great! Please merge to `master` and close the issue

**Comment by ubbeK** [comment]
Merge to master done!
