### ISSUE TITLE
Remove unneeded supplier partial

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Products#12]
Continued discussion from https://github.com/StarcounterSamples/Products/issues/11

------

@ubbeK wrote:

I have seen that the supplier, which is connected to the product, is shown twice when the application is running in standalone mode. 

![editproductpage_standalone_suppliernameshowntwice](https://cloud.githubusercontent.com/assets/8124023/14344233/a95339b2-fca6-11e5-98e5-fb89007a49c3.PNG)

**Comment by warpech** [comment]
@tomalec wrote:

> Ah right, so that element is also present when Launcher is running,

it is

> but is hidden because of "duck shooting". I added a not to explain "duck shooting"

Entire partial is hidden in layout hint, as it was hidden with default layout given in SQL
https://github.com/StarcounterSamples/Products/blob/feature_product_BEM_issue_11/src/Products/wwwroot/Products/viewmodels/ProductSupplierPage.html#L21

My question is whether we need this partial here or not? I think that providing a (visual) widget that is  hidden by default, only increases confusion.

So I would either:
1. Make `<starcounter-include>` visible bu default (via layout hint), but remove `SupplierPage.html` - other apps would be able to put smth there, but Products won't duplicate itself.
2. Remove both `<starcounter-include>` for supplier partial, and `SupplierPage.html`

I do not find a reason to keep `SupplierPage.html` in this app.

**Comment by warpech** [comment]
For me the answer is not that obvious. 

I would actually like to see supplier's details coming from People app - but it should be more than just an input with the name.

**Comment by tomalec** [comment]
> coming from People app

That's the thing, People is the app that manages Companies, and Products already has the input for name, so I think we do not need another tile with "just an input with the name".

When we will remove `SupplierPage.html` from Products and keep `<starcounter-include>` for Suppliers partial, then you will get Product page, with input to select the supplier, and supplier's detaild comming from People

**Comment by warpech** [comment]
> When we will remove SupplierPage.html from Products and keep <starcounter-include> for Suppliers partial, then you will get Product page, with input to select the supplier, and supplier's detaild comming from People

But Suppliers partial is like Schroedinger's box. The response from the People app may or may not be there. That's why Products app includes its own response.

**Comment by tomalec** [comment]
Are you saying that, if we will not provide `SuppliersPage.html` in Products, `<starcounter-include>` will not be able to get People's response?

if so `SupplierPage.html` could be empty.

**Comment by warpech** [comment]
Looks like this is done now?

**Comment by warpech** [comment]
Closing as done
