### ISSUE TITLE
Remove usage of dom-bind-notifier

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Products#14]
@diliger, can you do this while working on the current changes?

Part of https://github.com/Starcounter/Starcounter/issues/3568

**Comment by diliger** [comment]
I found dom-bind-notifier in the Products app only at one place on the [SupplierPage#L12](https://github.com/StarcounterSamples/Products/blob/master/src/Products/wwwroot/Products/viewmodels/SupplierPage.html#L12).

`
<dom-bind-notifier observed-object="{{model}}" path="model" deep juicy-style="
            itemName: dom-bind-notifier;
            hidden: true;
        "></dom-bind-notifier>
`

Should I just remove it and push?

**Comment by warpech** [comment]
Yes

**Comment by diliger** [comment]
Done.
