### ISSUE TITLE
There are SVG/JS errors in timeline graph

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Products#25]
When I visit some products, or select some shops, I see some errors in the Chrome console coming from the timeline graph: 

```
Error: <text> attribute x: Expected length, "NaN"
Error: <rect> attribute x: Expected length, "NaN"
Error: <g> attribute transform: Expected number, "translate(NaN,0)".
```

See the following recording:

![screen](https://cloud.githubusercontent.com/assets/566463/17581903/f0be335a-5fa8-11e6-9b64-839496d709f2.gif)

**Comment by diliger** [comment]
Fixed.
