### ISSUE TITLE
Replace the usage of the Page class with middleware

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Products#28]
Please replace the usage of the Page class with middleware, since the Page class is obsolete (see https://github.com/Starcounter/Starcounter/issues/3202). The instructions are in the blog post: http://starcounter.io/replace-page-partial-classes-middleware/

**Comment by diliger** [comment]
Done.

**Comment by warpech** [comment]
Please feel free to close the issues that are done. Thanks!
