### ISSUE TITLE
Old binding to server-side

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterSamples/Products#34]
In [EditProductPage.json](https://github.com/StarcounterSamples/Products/blob/master/src/Products/ViewModels/EditProductPage.json) we are using the old way of binding to the server side. 

```
"$Barcode$": { "Bind": "Barcode.Code" }
```

I don't know the impact of this, though it probably should get fixed.

**Comment by Mackiovello** [comment]
This also appears in the [People app](https://github.com/StarcounterSamples/People/blob/master/src/People/ViewModels/OrganizationsPage.json) and probably some more places

**Comment by Mnosek** [comment]
Are you sure that it already works in stable? Take a look here: https://github.com/Starcounter/Starcounter/issues/2964, implicit binding was pushed to develop/pnext just some time age.

**Comment by Mackiovello** [comment]
@Mnosek I'm not quite sure what you're talking about. 

As you say, this type of binding has been phased out. Because of that, I thought that we should update it to the current way of doing it. Again, I might be misunderstanding things completely.

**Comment by Mnosek** [comment]
You're absolutely right that we should keep it updated. What I meant was that I'm not 100% sure if bindings work in current stable version of Starcounter (2.2.1.3234) or only on pnext/develop branch (it's quite new feature). I think that couple days ago @warpech was unable to use it in stable.

**Comment by Mackiovello** [comment]
Thank you for the clarification. I'll look into it

**Comment by warpech** [comment]
Thanks for paying attention. Starcounter stable was released from `develop` branch in October, and this change was implemented in July, so yes, it is included in stable.

But as always, @Mackiovello please test such changes on Starcounter stable to be sure.

It is very welcome update, it is nice that you took this initiative.

**Comment by Mackiovello** [comment]
This isnow  fixed in the People and Products app
