### ISSUE TITLE
Make it work in IE

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/Products#6]

**Comment by warpech** [comment]
@ubbeK could you check if Products app now works ok in IE 11? 

The usual testing scenario for Products app is to test it with Launcher + Barcodes + Images app. Like on the following video:

https://www.dropbox.com/s/v0h2s578re71mw7/Products%2C%20Images%20and%20Barcodes%20in%2030s%20v2.mp4?dl=0

Please see if you are able to reproduce this setup. First in Chrome, then in Firefox, then in Edge, then in IE 11. Contact me on Hangouts when you hit some obstacles.

**Comment by ubbeK** [comment]
@miyconst: IE seems to be working besides issue [https://github.com/StarcounterSamples/Images/issues/23](url). Anything else that is not written in this issue or may I close it?

**Comment by miyconst** [comment]
Thank you for checking.

I close the issue since Products app is now working in IE.
