### ISSUE TITLE
Put labels and inputs on root; remove explicit standalone styles for form items

### ISSUE THREAD

**Issue by tomalec** [StarcounterSamples/Products#9]
In for example 
https://github.com/StarcounterSamples/Products/blob/master/src/Products/wwwroot/Products/viewmodels/EditProductPage.html#L20

```html
<div class="form-horizontal box-label">
    <label class="control-label">ID</label>
</div>
<div class="box-control">
    <input type="text" value="{{model.ID$::change}}" class="form-control" />
</div>
<div class="form-horizontal box-label">
    <label class="control-label">Name</label>
</div>
<div class="box-control">
    <input type="text" class="form-control" value="{{model.Name$::change}}" />
</div>
<div class="form-horizontal box-label">
    <label class="control-label">Barcode</label>
</div>
<div class="box-control">
    <input type="text" class="form-control" value="{{model.Barcode$::input}}" />
</div>
```

I see no point to wrap everything within `div`s, I suspect it's just legacy code from the times when `juicy-tile-*` was not wrapping tiles in shadow DOM.

For sure it makes applying predefined layouts harder (Starcounter/RebelsLounge#14), and even impossible without `<juicy-composer>`.

**Comment by tomalec** [comment]
@warpech, @miyconst Do you find any reason to keep those `div`s?

**Comment by miyconst** [comment]
This is to apply default bootstrap styles.

**Comment by tomalec** [comment]
So that is the thing @aloscha is working at?

**Comment by miyconst** [comment]
Yes, he is applying this pattern to KitchenSink project as far as I know.

**Comment by warpech** [comment]
This pattern in Products app was used to apply a 2-column layout to `EditProductPage.html` even when Launcher/juicy-tile-list is not running. As we just discussed on Hangouts with @tomalec, this *divitis* should be removed from Products. We will show this pattern at work in future, when layout composer understands more HTML patterns.

In KitchenSink ([`TextPage.html`](https://github.com/StarcounterSamples/KitchenSink/blob/41fc9d147b84e5aa25da9c94f1efffe960fba0f8/src/KitchenSink/wwwroot/KitchenSink/TextPage.html), etc), @aloscha has also applied a flat structure as well: 

```html
        <h5>Listening to changes</h5>

        <p>Bind to <code>::change</code> listener to send the new value to the server when the field is unfocused. Read more about the target change events in the <a href="https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#two-way-native">Polymer docs</a>.</p>

        <label class="control-label">{{model.NameReaction}}</label>

        <input type="text" value="{{model.Name$::change}}" placeholder="Name" class="form-control">
```

**Comment by tomalec** [comment]
I have moved items to the root, but standalone mode looks exactly as before. @warpech, do we mind keeping it?

**Comment by warpech** [comment]
Sure, if standalone mode still works, then event better for us! Closing
